%% Semantic Segmentation for Hurrican in Texas
% 
% Create Image label datastore

outputFolder = pwd;
imgDir = fullfile("D:\FDLData_new\",'pyramid_image');
imds = imageDatastore(imgDir);  % 读取原始图像
% Define classes

%%

classes = [ "background",...
    "Property_Roof",...
"Secondary_Structure",...
"Swimming_Pool",...
"Vehicle",...
"Grass",...
"Trees_Shrubs",...
"Solar_Panels",...
"Chimney",...
"Street_Light",...
"Window",...
"Satellite_Antenna"...
"Garbage_Bins",...
"Trampoline",...
"Road_Highway",...
"Under_Construction_In_Progress_Status",...
"Power_Lines_Cables",...
"Bridge",...
"Water_Tank_Oil_Tank",...
"Parking_Area_Commercial",...
"Sports_Complex_Arena",...
"Industrial_Site",...
"Dense_Vegetation_Forest",...
"Water_Body",...
"Flooded",...
"Boat",...
"Parking_Area"];
% Create Pixel label datastore

%%

labelDir = fullfile("D:\FDLData_new\",'pyramid_label');
labelID = 0:26;
pxds = pixelLabelDatastore(labelDir,classes,labelID);  % 读取像素点标签图像
% Label counts

% tbl = countEachLabel(pxds);
% disp(tbl)
% frequency = tbl.PixelCount/sum(tbl.PixelCount);
% 
% bar(1:numel(classes),frequency)
% xticks(1:numel(classes)) 
% xticklabels(tbl.Name) % 设置标签
% xtickangle(45)  % 调整x刻度的角度
% ylabel('Frequency')
% Define Image augmentation

%% Train, Val, Test split
[imdsTrain, imdsVal,~, pxdsTrain, pxdsVal, ~] = partitionData(imds,pxds, [0.75, 0.12]);


%% Data augmentation
imdsTrain = transform(imdsTrain, @(data) blurNoise(data));
dsTrain = combine(imdsTrain, pxdsTrain);

dsVal = combine(imdsVal, pxdsVal);
%% Load Networks
% Create resnet50.
%cd C:\Users\vipuser\FDLData_new
load deeplabv3plusresnet50.mat
% load net0119.mat

%% Set training options

if exist("D:\FDLData_new\checkpoint")==0
    mkdir("D:\FDLData_new\checkpoint")
end

options = trainingOptions('adam', ...
    "ExecutionEnvironment","gpu",...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropPeriod',4,...
    'LearnRateDropFactor',0.4,...
    'InitialLearnRate',1e-4, ...
    'ValidationData', dsVal,...
    'ValidationFrequency', 100,...
    'L2Regularization',0.05, ...
    'MaxEpochs',25, ...  
    'MiniBatchSize',20, ...
    'Shuffle','never', ...
    'CheckpointPath', "D:\FDLData_new\checkpoint", ...
    'VerboseFrequency',3,...
    'Plots','training-progress');
%    'CheckpointPath', "C:\Users\vipuser\FDLData_new\checkpoint", ...
% Train the model

%% save trained net
[net, info] = trainNetwork(dsTrain,lgraph,options);
save("net0119.mat","net")
% Model Evaludation

%% Evaluation on Test set
% predict using the trained net

pxdsResults = semanticseg(imdsTest,net, ...
    'MiniBatchSize',10, ...
    'WriteLocation',"D:\FDLData_new\pred_test", ...
    'Verbose',false,...
    'ExecutionEnvironment','gpu');

% evaluate on test set
metrics = evaluateSemanticSegmentation(pxdsResults,pxdsTest,'Verbose',false);

% view metrics
metrics.DataSetMetrics

% view label metrics
metrics.ClassMetrics

%% Make prediction
imgDir = fullfile("D:\FDLData_new\",'predict_image');
imdsPred = = imageDatastore(imgDir);  % 读取原始图像

pxdsResults = semanticseg(imdsPred,net, ...
    'MiniBatchSize',1, ...
    'WriteLocation',"D:\FDLData_new\pred_masks", ...
    'Verbose',false,...
    'ExecutionEnvironment','gpu');


